apiVersion: v1
kind: Service
metadata:
  labels:
    logging-infra: support
  name: kafka
  namespace: openshift-logging
spec:
  ports:
  - name: server
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    component: kafka
    provider: openshift
  sessionAffinity: None
  type: ClusterIP
