apiVersion: v1
kind: Service
metadata:
  labels:
    logging-infra: support
  name: zookeeper
  namespace: openshift-logging
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: peer
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: leader-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    component: zookeeper
    provider: openshift
  sessionAffinity: None
  type: ClusterIP
